modifica 7
Error:

Errore durante il salvataggio nel database.

ValueError: Unable to load PEM file. See https://cryptography.io/en/latest/faq/#why-can-t-i-import-my-pem-file for more details. InvalidData(Invalid padding)
Traceback:
File "/mount/src/app-caprilli-haccp/app_caprillign.py", line 160, in <module>
    hoja = obtener_hoja()
File "/mount/src/app-caprilli-haccp/app_caprillign.py", line 22, in obtener_hoja
    creds = Credentials.from_service_account_info(creds_dict, scopes=scopes)
File "/home/adminuser/venv/lib/python3.14/site-packages/google/oauth2/service_account.py", line 254, in from_service_account_info
    signer = _service_account_info.from_dict(
        info, require=["client_email", "token_uri"]
    )
File "/home/adminuser/venv/lib/python3.14/site-packages/google/auth/_service_account_info.py", line 57, in from_dict
    signer = crypt.RSASigner.from_service_account_info(data)
File "/home/adminuser/venv/lib/python3.14/site-packages/google/auth/crypt/base.py", line 109, in from_service_account_info
    return cls.from_string(
           ~~~~~~~~~~~~~~~^
        info[_JSON_FILE_PRIVATE_KEY], info.get(_JSON_FILE_PRIVATE_KEY_ID)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
File "/home/adminuser/venv/lib/python3.14/site-packages/google/auth/crypt/rsa.py", line 131, in from_string
    instance._impl = _cryptography_rsa.RSASigner.from_string(key, key_id=key_id)
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
File "/home/adminuser/venv/lib/python3.14/site-packages/google/auth/crypt/_cryptography_rsa.py", line 133, in from_string
    private_key = serialization.load_pem_private_key(
        key, password=None, backend=_BACKEND
    )